name: macOS Build

on:
  repository_dispatch:
    branches: [feature/dev]
    types: [bitbucket_push]

jobs:
  build:
    runs-on: macos-latest 

    steps:
    - name: Checkout Bitbucket repository
      run: |
        git clone ${{ secrets.BITBUCKET_URL }} bitbucket-repo
        
    - uses: subosito/flutter-action@v2
      name: 安装FLUTTER环境
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
    - run: cd bitbucket-repo && flutter clean && flutter pub get && cd macos/ && pod install
      name: 安装依赖
    
    - uses: apple-actions/import-codesign-certs@v3
      name: 安装P12_APPLICATION证书
      with:
        p12-file-base64: ${{ secrets.APPLICATION_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
        keychain: 'macos-application-keychain'
    
    - uses: apple-actions/import-codesign-certs@v3
      name: 安装P12_INSTALLER证书
      with:
        p12-file-base64: ${{ secrets.INSTALLER_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
        keychain: 'macos-installer-keychain'

    - name: Build project
      run: |
        echo "Building project..."
        cd bitbucket-repo
        ls
        mkdir -p dist

        flutter build macos --release --no-tree-shake-icons

        # 将/build/macos/Build/Products/Release/目录下的文件复制到dist目录下
        cp -r build/macos/Build/Products/Release/* dist/

        # echo "Build artifact 1" > dist/artifact1.txt  # 模拟构建产物
        # echo "Build artifact 2" > dist/artifact2.txt  # 模拟构建产物

    - name: Install coscli
      run: |
        curl -sSL https://github.com/tencentyun/coscli/releases/download/v1.0.4/coscli-v1.0.4-darwin-arm64 -o coscli
        sudo mv coscli /usr/local/bin/coscli
        chmod +x /usr/local/bin/coscli

    - name: Configure coscli
      run: |
        coscli config add \
          --bucket ${{ secrets.BUC_NAME }} \
          --region ap-beijing \
          --alias my-bucket
        coscli config set \
          --secret_id ${{ secrets.SEC_ID }} \
          --secret_key ${{ secrets.SEC_K }} 

    - name: Upload to COS
      run: |
        coscli cp dist/* cos://my-bucket/
