name: macOS Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest 

    steps:
    - name: Checkout Bitbucket repository
      run: |
        git clone -b master --single-branch --depth 1 ${{ secrets.BITBUCKET_URL }} bitbucket-repo
        
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.BITBUCKET_SSH_KEY }}
    - name: Add Bitbucket to known hosts
      run: ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts

    - uses: subosito/flutter-action@v2
      name: 安装FLUTTER环境
      with:
        flutter-version: '3.27.1'
        channel: 'stable'

    - name: 安装依赖
      run: |
        # 安装rust
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env

        # 安装 protoc
        PROTOC_ZIP=protoc-21.12-osx-x86_64.zip
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/$PROTOC_ZIP
        sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
        sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
        rm -f $PROTOC_ZIP

        # 安装rinf
        cargo install rinf --version 7.1.0
        
        # 构建 Protobuf 消息
        cd bitbucket-repo
        rinf message

        # 打印protobuf版本
        protoc --version

        # 确定输出目录
        dart run build_runner build --define "platform_builder:platform_builder=platform=macos"
        flutter clean
        flutter pub get
        cd macos/
        pod install

    - uses: apple-actions/import-codesign-certs@v1
      name: 安装APP证书
      with:
        p12-file-base64: ${{ secrets.APP_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}

    # - run: |
    #     security find-identity -v

    - name: Build project
      run: |
        echo "Building project..."
        cd bitbucket-repo
        mkdir -p dist
        
        flutter build macos --release --no-tree-shake-icons
        
        # 确定输出目录
        PROJECT_DIR=$(pwd)
        OUTPUT_DIR="$PROJECT_DIR/build/macos/Build/Products/Release"
        
        # 创建临时目录
        DMG_DIR="$OUTPUT_DIR/dmg_temp"
        if [[ -d "$DMG_DIR" ]]; then
         rm -rf "${DMG_DIR:?}/"*
        else
         mkdir -p "$DMG_DIR"
        fi
        
        # 获取应用程序名称
        APP_NAME=$(echo "$OUTPUT_DIR"/*.app | awk -F 'Release/' '{print $2}' | awk -F .app '{print $1}')

        # 应用程序大小
        APP_SIZE=$(du -sm $OUTPUT_DIR/*.app | awk '{print $1}')
        echo "App Size: ${APP_SIZE}M"

        # 计算目标大小，APP_SIZE + 5MB
        TARGET_SIZE=$((APP_SIZE + 5))
        
        # 获取tag
        TAG="${GITHUB_REF#refs/tags/}"
        echo "TAG=$TAG" >> $GITHUB_ENV

        # 确定DMG名称
        DMG_NAME="${APP_NAME}_${TAG}.dmg"
        echo "DMG_NAME=$DMG_NAME" >> $GITHUB_ENV
        
        # 应用签名
        codesign -f -o runtime --entitlements ./macos/Runner/Release.entitlements -s "${{secrets.IDENTITY_NAME}}" -v "${OUTPUT_DIR}/${APP_NAME}.app" --deep
        
        # 生成钥匙串密码凭证
        xcrun notarytool store-credentials 'pictorial' --apple-id "${{secrets.USER_NAME}}" --team-id "${{secrets.TEAM_ID}}" --password "${{secrets.ACCOUNT_PASSWORD}}"
        
        # 将应用程序复制到临时目录
        cp -R "$OUTPUT_DIR/$APP_NAME.app" "$DMG_DIR" || exit 1
        
        # 确定DMG路径
        DMG_PATH="$OUTPUT_DIR/$DMG_NAME"
        echo "DMG_PATH=$DMG_PATH" >> $GITHUB_ENV
        
        # 创建DMG文件
        # hdiutil create -volname 'Pictorial' -srcfolder "$DMG_DIR" -ov -format UDZO "$DMG_PATH"
        # 创建空的DMG文件
        hdiutil create -size ${TARGET_SIZE}m -fs APFS -volname "$APP_NAME" -srcfolder "$DMG_DIR" -ov -format UDRW "$DMG_PATH"

        # 挂载 DMG
        MOUNT_POINT="/Volumes/$APP_NAME"
        hdiutil attach "$DMG_PATH" -mountpoint "$MOUNT_POINT"

        # 创建符号链接
        ln -s /Applications /Volumes/"$APP_NAME"

        # 卸载 DMG
        hdiutil detach "$MOUNT_POINT"

        # 转换为只读 DMG
        hdiutil convert "$DMG_PATH" -format UDZO -o "${DMG_PATH%.dmg}-tmp.dmg"

        # 删除原始可写 DMG
        rm -rf "$DMG_PATH"

        # 重命名最终 DMG 文件
        mv "${DMG_PATH%.dmg}-tmp.dmg" "$DMG_PATH"
        echo "DMG 创建完成: $DMG_PATH"
        
        # 提交到公证服务
        xcrun notarytool submit "$DMG_PATH" --keychain-profile "pictorial" --wait --no-s3-acceleration
        
        # 注入公证信息
        xcrun stapler staple "$DMG_PATH"
        
        # 删除临时目录
        rm -rf "$DMG_DIR"
    
    # 检查 ${{ env.DMG_PATH }} 是否存在
    - name: Check DMG file
      run: |
        if [ ! -f "${{ env.DMG_PATH }}" ]; then
          echo "DMG file not found"
          exit 1
        fi

    # 4. 发布 DMG 到 Release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: "${{ env.DMG_PATH }}"
        name: "Auto Release ${{ github.sha }}"
        body: "DMG package for commit ${{ github.sha }}"
        draft: false
        prerelease: true  # 标记为预发布
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        
    - name: Send success notification to WeChat
      if: success()
      run: |
        curl -X POST "${{ secrets.WECHAT_HOOK }}" \
        -H 'Content-Type: application/json' \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "构建成功: ${{ secrets.FILE_URL }}/${{ env.TAG }}/${{ env.DMG_NAME }}"
              }
            }'

    - name: Send failure notification to WeChat
      if: failure()
      run: |
        curl -X POST "${{ secrets.WECHAT_HOOK }}" \
        -H 'Content-Type: application/json' \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "构建失败"
              }
            }'
