name: macOS Build

on:
  repository_dispatch:
    branches: [feature/dev]
    types: [bitbucket_push]

jobs:
  build:
    runs-on: macos-latest 

    steps:
    - name: Checkout Bitbucket repository
      run: |
        git clone ${{ secrets.BITBUCKET_URL }} bitbucket-repo
        
    - uses: subosito/flutter-action@v2
      name: 安装FLUTTER环境
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
    - run: cd bitbucket-repo && flutter clean && flutter pub get && cd macos/ && pod install
      name: 安装依赖
    
    - uses: apple-actions/import-codesign-certs@v1
      name: 安装P12_APPLICATION证书
      with:
        p12-file-base64: ${{ secrets.APPLICATION_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
        keychain: 'macos-application-keychain'
    
    - uses: apple-actions/import-codesign-certs@v3
      name: 安装P12_INSTALLER证书
      with:
        p12-file-base64: ${{ secrets.INSTALLER_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
        keychain: 'macos-installer-keychain'

    - name: Build project
      run: |
        echo "Building project..."
        cd bitbucket-repo
        ls
        mkdir -p dist

        flutter build macos --release --no-tree-shake-icons

        echo ">>>>>1"
        security find-identity -v
        echo ">>>>>2"

        # 确定输出目录
        PROJECT_DIR=$(pwd)
        OUTPUT_DIR="$PROJECT_DIR/build/macos/Build/Products/Release"

        # 创建临时目录
        DMG_DIR="$OUTPUT_DIR/dmg_temp"
        if [[ -d "$DMG_DIR" ]]; then
            rm -rf "${DMG_DIR:?}/"*
        else
            mkdir -p "$DMG_DIR"
        fi

        # 获取应用程序名称
        APP_NAME=$(echo "$OUTPUT_DIR"/*.app | awk -F 'Release/' '{print $2}' | awk -F .app '{print $1}')

        # 获取当前时间
        CURRENT_TIME=$(date "+%Y%m%d_%H%M")

        # 确定DMG名称
        DMG_NAME="${APP_NAME}_${CURRENT_TIME}.dmg"

        # 应用签名
        # codesign -f -o runtime -s "${{secrets.IDENTITY_NAME}}" -v "${OUTPUT_DIR}/${APP_NAME}.app" --deep
        codesign -f -o runtime -s "macos-application-keychain" -v "${OUTPUT_DIR}/${APP_NAME}.app" --deep

        # 生成钥匙串密码凭证
        xcrun notarytool store-credentials 'pictorial' --apple-id "${{secrets.USER_NAME}}" --team-id "${{secrets.TEAM_ID}}" --passwrod "${{secrets.ACCOUNT_PASSWORD}}"

        # 将应用程序复制到临时目录
        cp -R "$OUTPUT_DIR/$APP_NAME.app" "$DMG_DIR" || exit 1

        # 确定DMG路径
        DMG_PATH="$OUTPUT_DIR/$DMG_NAME"

        # 输出DMG路径
        echo ">>>>>> DMG path: $DMG_PATH"

        # 创建DMG文件
        hdiutil create -volname 'Pictorial' -srcfolder "$DMG_DIR" -ov -format UDZO "$DMG_PATH"

        # 提交到公证服务
        xcrun notarytool submit "$DMG_PATH" --keychain-profile "pictorial" --wait --no-s3-acceleration

        # 注入公证信息
        xcrun stapler staple "$DMG_PATH"

        # 删除临时目录
        rm -rf "$DMG_DIR"

        # 检查DMG是否创建成功
        if [ -f "$DMG_PATH" ]; then
            # 将/build/macos/Build/Products/Release/目录下的文件复制到dist目录下
            cp "$DMG_PATH" dist/
        else
            echo "Failed to create DMG"
            exit 1
        fi

        # 删除构建产物
        # rm -rf "$OUTPUT_DIR"

        # echo "Build artifact 1" > dist/artifact1.txt  # 模拟构建产物
        # echo "Build artifact 2" > dist/artifact2.txt  # 模拟构建产物

    - name: Install coscli
      run: |
        curl -sSL https://github.com/tencentyun/coscli/releases/download/v1.0.4/coscli-v1.0.4-darwin-arm64 -o coscli
        sudo mv coscli /usr/local/bin/coscli
        chmod +x /usr/local/bin/coscli

    - name: Configure coscli
      run: |
        coscli config add \
          --bucket ${{ secrets.BUC_NAME }} \
          --region ap-beijing \
          --alias my-bucket
        coscli config set \
          --secret_id ${{ secrets.SEC_ID }} \
          --secret_key ${{ secrets.SEC_K }} 

    - name: Upload to COS
      run: |
        cd bitbucket-repo
        ls dist
        coscli cp "dist/" "cos://my-bucket/" -r
